baseURL = "https://heidiwilliamsfoy.space/"
languageCode = "en-us"
title = "Heidi Williams-Foy"
theme = "sam"

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/about"
    text = "about"

